In [1]:
import numpy as np

In [13]:
H = (1/np.sqrt(2))*np.matrix([[1, 1],
                              [1, -1]])

In [14]:
H

matrix([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]])

In [15]:
X = np.matrix([[0, 1], 
              [1, 0]])

In [16]:
X

matrix([[0, 1],
        [1, 0]])

In [17]:
Z = np.matrix([[1, 0],
               [0, -1]])

In [18]:
Z

matrix([[ 1,  0],
        [ 0, -1]])

In [19]:
np.dot(H, np.dot(X, H))

matrix([[ 1.00000000e+00,  2.23711432e-17],
        [-2.23711432e-17, -1.00000000e+00]])

In [26]:
np.dot(H, np.dot(Z, H))

matrix([[-2.23711432e-17,  1.00000000e+00],
        [ 1.00000000e+00, -2.23711432e-17]])

In [22]:
S = np.matrix([[1, 0],
               [0, 1j]])

In [27]:
np.dot(S, np.dot(X, S.H))

matrix([[0.+0.j, 0.-1.j],
        [0.+1.j, 0.+0.j]])

In [29]:
np.dot(S, np.dot(Z, S.H))

matrix([[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]])

In [30]:
Z

matrix([[ 1,  0],
        [ 0, -1]])